# collectionbuilder-gh
# a Jekyll Digital Collection Generator
# designed for GitHub Pages

# Site settings

# title of site appears in banner
title: CDIL
# tagline appears in banner
tagline: a theme for building simple digital exhibits
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "CollectionBuilder-GH is a template for creating small digital collection exhibits on GitHub Pages designed for teaching digital library skills"
# keywords appear in meta tags
keywords: "university of idaho, digital collections, digital humanities"
# creator of the digital collection, to appear in meta tags
author: dcnb
# creator contact email for meta tags
email: dbecker@uidaho.edu
# collection project date, when did you publish this
collection-date: "2019"

# url is your gh-pages base, following the pattern: username.github.io
url: https://thecdil.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: 
# repository is the github repository's full url
repository: https://github.com/thecdil/cdil_source

# Theme Options
# Use fontawesome CDN (true, false), https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css
fontawesome: true
# navbar text color
# Choose from "navbar-light" for use with light background colors, or "navbar-dark" for dark background colors
# navbar-color: navbar-dark
# navbar background color
# Choose from bg-primary, bg-secondary, bg-success, bg-danger, bg-warning, bg-info, bg-light, bg-dark, bg-white
# navbar-background: bg-secondary
# theme with Bootswatch (https://github.com/thomaspark/bootswatch)
# Choose from: cerulean; cosmo; cyborg; darkly; flatly; journal; litera; lumen; lux; materia; minty; pulse; sandstone; simplex; sketchy; slate; solar; spacelab; superhero; united; yeti 
bootswatch: true # leave blank or comment out for plain bootstrap

page_gen:
  - data: 'projects'
    template: 'project-page'
    name: 'projectid'
    dir: 'projects'
    extension: 'html'   


# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
